# ===================================================================
# Spring Boot configuration for the "gae" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  port: ${PORT}
management:
  health:
    diskspace:
      enabled: false
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:postgresql://google/lodigital?cloudSqlInstance=lo-digital:northamerica-northeast1:backend&socketFactory=com.google.cloud.sql.postgres.SocketFactory'
    username: 'fvilches'
    password: '292403'
    hikari:
      maximumPoolSize: 8
